# code_genius.py
"""
🧠 Bruce – Code Genius Engine
Generador multilenguaje, adaptativo y simbótico de código fuente avanzado.
"""

from datetime import datetime
from deepseek_editor import DeepSeekEditor
from personality import TraderProfile
from self_reflection import SelfReflection
import uuid

# Diccionario de lenguajes soportados con plantillas mínimas
LANGUAGE_TEMPLATES = {
    "python": "print('Hello World')",
    "javascript": "console.log('Hello World');",
    "typescript": "console.log('Hello World')",
    "c": '#include <stdio.h>\nint main() { printf("Hello World"); return 0; }',
    "cpp": '#include <iostream>\nint main() { std::cout << "Hello World"; return 0; }',
    "java": 'public class Main { public static void main(String[] args) { System.out.println("Hello World"); } }',
    "go": 'package main\nimport "fmt"\nfunc main() { fmt.Println("Hello World") }',
    "rust": 'fn main() { println!("Hello World"); }',
    "solidity": 'pragma solidity ^0.8.0;\ncontract HelloWorld { function greet() public pure returns (string memory) { return "Hello World"; } }',
    "bash": 'echo "Hello World"',
    "powershell": 'Write-Output "Hello World"',
    "html": "<!DOCTYPE html><html><body><h1>Hello World</h1></body></html>",
    "css": "body { font-family: Arial; background: #f0f0f0; }",
    "sql": "SELECT 'Hello World';",
    "lua": 'print("Hello World")',
    "swift": 'print("Hello World")',
    "kotlin": 'fun main() { println("Hello World") }',
    "r": 'print("Hello World")',
    "perl": 'print "Hello World\\n";',
    "php": '<?php echo "Hello World"; ?>',
    "haskell": 'main = putStrLn "Hello World"',
    # Extensible...
}

class BruceCodeGenerator:
    """
    🤖 Módulo simbótico de generación de código fuente por Bruce.
    Con historial persistente, perfil trader y reflexión cognitiva.
    """
    def __init__(self):
        self.history = []
        self.editor = DeepSeekEditor()
        self.persona = TraderProfile()
        self.reflection = SelfReflection()

    def generate(self, description: str, language: str = "python") -> dict:
        lang = language.lower()
        now = datetime.utcnow().isoformat()
        profile = self.persona.current_profile()
        reflection_data = self.reflection.evaluate()
        doc_comment = f"# Code generated by Bruce | Profile: {profile} | Knowledge: {reflection_data['known']} | Needs: {reflection_data['unknown']}"

        template = LANGUAGE_TEMPLATES.get(lang, f"// Unsupported language: {lang}\n// TODO: Implement logic for: {description}")

        code = f"""{doc_comment}
# Task: {description}
# Date: {now}

{template}
"""

        record = {
            "id": str(uuid.uuid4()),
            "language": lang,
            "description": description,
            "generated_code": code,
            "meta": {
                "profile": profile,
                "reflection": reflection_data,
                "timestamp": now,
                "suggestions": "Puedes mejorar este código integrando BruceEditor o evaluando errores en tiempo real."
            }
        }

        self.history.append(record)
        return record

    def get_history(self):
        return {
            "total_generated": len(self.history),
            "records": self.history
        }

    def suggest_improvements(self, code_snippet: str) -> str:
        # Placeholder para futuras integraciones de DeepSeek AI
        return self.editor.review_code(code_snippet)
